config/routes.rb
Rails.application.routes.draw do
  
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}


# 「devise_scope」メソッドは、Deviseが提供するセッション関連の機能をカスタマイズ
devise_scope :admin do
  get '/admin/sign_out' => 'devise/sessions#destroy'
  get ENV['ADMIN_ROUTING'] => 'devise/registrations#new'
end

devise_scope :customer do
  post "/customers/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  
  #namespace :admin doはルーティングをグループ化するための機能
  namespace :admin do
    # get 'orders/show'
    resources :orders,only: [:show, :update]
    resources :order_details,only: [:update]
    
    # get 'customers/index'
    # get 'customers/show'
    # get 'customers/edit'
    resources :customers, only: [:index, :show, :edit, :update]
    
    # get 'production_areas/index'
    # get 'production_areas/edit'
    resources :production_areas, only: [:index, :show,:create, :edit, :update]
    
    # get 'items/index'
    # get 'items/new'
    # get 'items/edit'
    # get 'items/show'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    
    resources :rooms, only: %i(index show)
    resource :message, only: :create
    
    get '/contact/:customer_id' => 'messages#show', as: :contact
    post '/contact/:customer_id' => 'messages#create'
    get '/messages' => 'messages#index'
    
    # get 'homes/top'
    root to: 'homes#top'
  end
  
  namespace :public, path: '/' do
    # get 'addresses/index'
    # get 'addresses/edit'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    # get 'cart_items/index'
    delete 'cart_items/destroy_all', as:'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    # get 'customers/show'
    # get 'customers/edit'
    get 'customers/unsubscribe'
    resources :customers, only: [:show, :edit, :update]
    
    get 'items/index'
    get 'items/show'
    resources :items, only: [:index, :show]
    
    # get 'orders/confirm'
    get 'orders/thanks', as: 'thanks'
    post 'orders/confirm'
    resources :orders,only: [:new, :index, :show, :create]
    
    root to: 'homes#top'
    # get 'homes/top'
    get 'homes/about'
    
    get '/contact' => 'messages#show'
    post '/contact' => 'messages#create'
    resources :rooms, only: %i(index show)
    resource :message, only: :create
    
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :admin, optional: true
  # belongs_to :room

  validates :message, presence: true
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < Admin::ApplicationController
  
  def index 
    @customer = Customer.all
    # @messages = Message.all
  end
  
  def show 
    @customer = Customer.find(params[:customer_id])
  end
  
  def create
    message = Message.new(message_params)
    message.customer_id = params[:customer_id]
    message.from = 0
    if message.save
      redirect_to request.referer
    else
      redirect_to request.referer, alert: 'メッセージを送信できませんでした'
    end
  end

  private
  def message_params
    params.require(:message).permit(:message).merge(admin_id: current_admin.id)
  end
end

app/views/admin/messages/index.html.erb
 <h5 style="width: 90px; margin:30px 0 20px 200px;">会員一覧</h5>
 <div class="container">
  <div class="row py-4 px-auto">
      <table class="table table-bordered ">
       <thead class="table-active">
         <tr>
           <th>企業名</th>
           <th>メッセージ</th>
         </tr>
       </thead>
       <% @customer.each do |customer| %>
      <tr>
        <td><%= customer.enterprise_name %></td>
        <td><%= link_to "メッセージを確認", admin_contact_path(customer.id)%></td>
      </tr>
       <% end %>
      </table>
  </div>
</div>

app/views/admin/messages/show.html.erb
<div class="container">
  <div class="col-6 mx-auto" style="background-color: white">
    <% @customer.messages.each do |message| %>
      <% if message.from == 1 %>
        <div class="text-right mb-2">
          <small class="d-block">
            <%= link_to message.customer.enterprise_name, admin_customer_path(message.customer) %>
          </small>
          <small class="d-block text-black-50">
            <%= message.created_at.in_time_zone('Asia/Tokyo').strftime('%Y年%m月%d日 %H時%M分') %>
          </small>
          <%= simple_format(message.message, sanitize: true, class: "m-0") %>
        </div>
      <% else %>
        <div class="text-left mb-2">
          <small class="d-block text-black-50">
            オーナー
          </small>
          <small class="d-block text-black-50">
            <%= message.created_at.in_time_zone('Asia/Tokyo').strftime('%Y年%m月%d日 %H時%M分') %>
          </small>
          <%= simple_format(message.message, sanitize: true, class: "m-0") %>
        </div>
      <% end %>
    <% end %>

    <div class="mt-3">
      <%= form_with(model: Message.new, url: admin_contact_path(@customer.id), local: true) do |f| %>
        <div class="form-group">
          <%= f.label :message, "問い合わせ内容" %>
          <%= f.text_area :message, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit '送信',class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
    
  </div>
</div>