config/routes.rb
Rails.application.routes.draw do
  
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}


# 「devise_scope」メソッドは、Deviseが提供するセッション関連の機能をカスタマイズ
devise_scope :admin do
  get '/admin/sign_out' => 'devise/sessions#destroy'
  get ENV['ADMIN_ROUTING'] => 'devise/registrations#new'
end

devise_scope :customer do
  post "/customers/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  
  #namespace :admin doはルーティングをグループ化するための機能
  namespace :admin do
    # get 'orders/show'
    resources :orders,only: [:show, :update]
    resources :order_details,only: [:update]
    
    # get 'customers/index'
    # get 'customers/show'
    # get 'customers/edit'
    resources :customers, only: [:index, :show, :edit, :update]
    
    # get 'production_areas/index'
    # get 'production_areas/edit'
    resources :production_areas, only: [:index, :show,:create, :edit, :update]
    
    # get 'items/index'
    # get 'items/new'
    # get 'items/edit'
    # get 'items/show'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    
    resources :rooms, only: %i(index show)
    resource :message, only: :create
    
    get '/contact/:customer_id' => 'messages#show', as: :contact
    post '/contact/:customer_id' => 'messages#create'
    get '/messages' => 'messages#index'
    
    # get 'homes/top'
    root to: 'homes#top'
  end
  
  namespace :public, path: '/' do
    # get 'addresses/index'
    # get 'addresses/edit'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    # get 'cart_items/index'
    delete 'cart_items/destroy_all', as:'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    # get 'customers/show'
    # get 'customers/edit'
    get 'customers/unsubscribe'
    resources :customers, only: [:show, :edit, :update]
    
    get 'items/index'
    get 'items/show'
    resources :items, only: [:index, :show]
    
    # get 'orders/confirm'
    get 'orders/thanks', as: 'thanks'
    post 'orders/confirm'
    resources :orders,only: [:new, :index, :show, :create]
    
    root to: 'homes#top'
    # get 'homes/top'
    get 'homes/about'
    
    get '/contact' => 'messages#show'
    post '/contact' => 'messages#create'
    resources :rooms, only: %i(index show)
    resource :message, only: :create
    
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/production_area.rb
class ProductionArea < ApplicationRecord
   has_many :items, dependent: :destroy
   
    validates :name, presence: true
end

app/controllers/admin/production_areas_controller.rb
class Admin::ProductionAreasController < ApplicationController
   before_action :authenticate_admin!
   
  def index
    @production_area = ProductionArea.new
    @production_areas = ProductionArea.all
  end
  
  def create
      @production_area =ProductionArea.new(production_area_params)
    if @production_area.save
      redirect_to admin_production_areas_path
    else
      flash[:alert] = "産地を入力してください。"
      @production_area = ProductionArea.new
      @production_areas = ProductionArea.all
      render :index
    end
  end

  def edit
    @production_area = ProductionArea.find(params[:id])
  end
  
  def update
    @production_area = ProductionArea.find(params[:id])
    if @production_area.update(production_area_params)
      redirect_to admin_production_areas_path
    else
      @production_area = ProductionArea.find(params[:id])
      render :edit
    end
  end
  
   private
  def production_area_params
    params.require(:production_area).permit(:name)
  end
end

app/helpers/admin/production_areas_helper.rb
module Admin::ProductionAreasHelper
end

app/views/admin/production_areas/edit.html.erb
<%= render 'layouts/error', obj: @production_area %>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2"></div>
       <div class="col my-4">
         <h5 class="bg-secondary" style="width: 130px;">産地編集</h5>
       </div>
    </div>

    <div class="row ml-5 my-5">
      <p class="font-weight-bold ml-4">産地名</p>
      <%= form_with model: @production_area, url: admin_production_area_path(@production_area.id), method: :patch do |f| %>
        <%= f.text_field :name,class:"mx-5"%>
        <%= f.submit '変更を保存',class:"btn btn-success" %>
      <% end %>
   </div>
</div>

app/views/admin/production_areas/index.html.erb
<%= content_tag :div,flash[:notice], style:"margin:20px 0 0 220px;" %>

<%= render 'layouts/error', obj: @production_area %>

<div class="container-fluid">
    <div class="row">
        <div class="col-2"></div>
       <div class="col my-4">
         <h5 style="width: 190px;">産地一覧・追加</h5>
       </div>
    </div>

    <div class="row ml-5 my-5">
       <p class="font-weight-bold ml-4">産地名</p>
    　 <%= form_with model: @production_area, url: '/admin/production_areas', method: :post do |f| %>
           <%= f.text_field :name,class:"mx-5"%>
           <%= f.submit '新規登録',class:"btn btn-success" %>
       <% end %>
    </div>

    <div class="row mx-5">
        <div class="col-md-7">
            <table class="table">
                <thead class="table-active">
                    <tr>
                      <th></th>
                      <th><h5 class="font-weight-bold">産地</h5></th>
                      <th></th>
                    </tr>
                </thead>
                <tbody>
                       <% @production_areas.each do |production_area| %>
                       <tr>
                       <td><%= production_area.name %></td>
                       <td></td>
                       <td>
                        <%= link_to "編集する", edit_admin_production_area_path(production_area.id),class: "btn btn-success" %>
                        <% end %>
                       </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>