config/routes.rb
Rails.application.routes.draw do
  
    # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, controllers: {
  sessions: "admin/sessions"
}


# 「devise_scope」メソッドは、Deviseが提供するセッション関連の機能をカスタマイズ
devise_scope :admin do
  get '/admin/sign_out' => 'devise/sessions#destroy'
  get ENV['ADMIN_ROUTING'] => 'devise/registrations#new'
end

devise_scope :customer do
  post "/customers/guest_sign_in", to: "public/sessions#guest_sign_in"
end

  
  #namespace :admin doはルーティングをグループ化するための機能
  namespace :admin do
    # get 'orders/show'
    resources :orders,only: [:show, :update]
    resources :order_details,only: [:update]
    
    # get 'customers/index'
    # get 'customers/show'
    # get 'customers/edit'
    resources :customers, only: [:index, :show, :edit, :update]
    
    # get 'production_areas/index'
    # get 'production_areas/edit'
    resources :production_areas, only: [:index, :show,:create, :edit, :update]
    
    # get 'items/index'
    # get 'items/new'
    # get 'items/edit'
    # get 'items/show'
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
    
    resources :rooms, only: %i(index show)
    resource :message, only: :create
    
    get '/contact/:customer_id' => 'messages#show', as: :contact
    post '/contact/:customer_id' => 'messages#create'
    get '/messages' => 'messages#index'
    
    # get 'homes/top'
    root to: 'homes#top'
  end
  
  namespace :public, path: '/' do
    # get 'addresses/index'
    # get 'addresses/edit'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    
    # get 'cart_items/index'
    delete 'cart_items/destroy_all', as:'destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    
    # get 'customers/show'
    # get 'customers/edit'
    get 'customers/unsubscribe'
    resources :customers, only: [:show, :edit, :update]
    
    get 'items/index'
    get 'items/show'
    resources :items, only: [:index, :show]
    
    # get 'orders/confirm'
    get 'orders/thanks', as: 'thanks'
    post 'orders/confirm'
    resources :orders,only: [:new, :index, :show, :create]
    
    root to: 'homes#top'
    # get 'homes/top'
    get 'homes/about'
    
    get '/contact' => 'messages#show'
    post '/contact' => 'messages#create'
    resources :rooms, only: %i(index show)
    resource :message, only: :create
    
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  with_options presence: true do
    validates :post_code
    validates :address
    validates :name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :messages, dependent: :destroy

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  #小計を求めるメソッド
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items
  has_many :messages, dependent: :destroy


  with_options presence: true do
    validates :enterprise_name
    validates :enterprise_name_kana
    validates :post_code
    validates :address
    validates :telephone_number
    validates :email
  end
  
  # 定数にメールアドレスを格納
  GUEST_CUSTOMER_EMAIL = "guest@example.com"

  def self.guest
    # find_or_create_byでメールアドレスが存在するかどうか判断。存在しない場合はデータを作成する。
    find_or_create_by(email: GUEST_CUSTOMER_EMAIL) do |customer|
      # SecureRandom.urlsafe_base64:ランダムな文字列を生成するRubyのメソッド
      customer.password = SecureRandom.urlsafe_base64
      customer.enterprise_name = "guest customer"
      customer.enterprise_name_kana = "ゲスト カスタマー"
      customer.post_code = "0010000"
      customer.address = "北海道札幌市北区"
      customer.telephone_number = "00000000000"
    end
  end
  
  # ref: https://qiita.com/Naggi-Goishi/items/49f758608f93286a3701
  def active_for_authentication?
    super && is_customer_status?
  end
  
  def inactive_message
    is_customer_status? ? super : :status_false
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  has_one :room, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :customers, through: :cart_items
  has_many :order_details
  
  belongs_to :production_area
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion:{in: [true, false]}
  validates :production_area_id, presence: true
  
  has_one_attached :image
  # enum is_active: { on_sale: 0, off_sale: 1 }
  
  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :admin, optional: true
  # belongs_to :room

  validates :message, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  
  validates :post_code,presence:true
  validates :name,presence:true
  validates :address,presence:true
  validates :delivery_date,presence:true
  validates :payment_method,presence:true
  
  enum payment_method: {credit_card: 0, transfer: 1}

  enum order_status: {wait_payment: 0, 
                      confirm_payment: 1, 
                      making: 2, 
                      preparing_ship: 3, 
                      finish_prepare: 4
                      }
  
  # enum payment_method: {クレジットカード: 0, 銀行振込: 1}
  
  # enum order_status: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum making_status: { 
          making_unable: 0, 
          waiting_for_making: 1, 
          in_making: 2, 
          making_completed: 3 
        }
        
  def with_tax_price
    ( item.price * 1.1).floor
  end
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/production_area.rb
class ProductionArea < ApplicationRecord
   has_many :items, dependent: :destroy
   
    validates :name, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :entry
  has_many :messages, dependent: :destroy

  validates :entry_id, uniqueness: true
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   before_action :authenticate_admin!
  def new
    @item = Item.new
    @production_areas = ProductionArea.all
  end
  
  def create
      @item = Item.new(item_params)
    if @item.save!
      redirect_to admin_item_path(@item.id)
    else
      @production_areas = ProductionArea.all
      render :new
    end
  end
  
  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
    @production_areas = ProductionArea.all
  end
  
  def update
    @item = Item.find(params[:id])
     if @item.update!(item_params)
       redirect_to admin_item_path(@item.id)
     else
       @item = Item.find(params[:id])
       @production_areas = ProductionArea.all
       render :edit
     end
  end

  def show
    @item = Item.find(params[:id])
  end
  
   private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :production_area_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "") %> 件のエラーが出ています。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<body>
  <footer style="background-color:  #FFC0CB; color: #000; padding: 20px;">
    <div class="container">
      <p class="text-center m-0">Meet Order</p>
    </div>
  </footer>
</body>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-expand-lg navbar-dark">
    <div class="container-lg">
        <div class="col-md-2">
          <% if admin_signed_in? %>
            <div class="navbar-brand">Meet Order</div>
          <% else %>
           <%= link_to public_root_path do %>
             <div class="navbar-brand">Meet Order</div>
           <% end %>
          <% end %>
        </div>
        <div class="col-md-3 text-center">
          <!-- 中央にようこそ〇〇さん！を配置 -->
          <% if customer_signed_in? %>
            <div class="text-light">ようこそ <%= current_customer.enterprise_name %> さん！</div>
          <% end %>
        </div>
        
        <div class="col-md-7">
          <div class="row">
            <div class="col-md-12">
              <!-- 上段にナビゲーションを配置 -->
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                  </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <div class="navbar-nav">
                <% if admin_signed_in? %>
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "注文履歴一覧", admin_root_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "産地一覧", admin_production_areas_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "DM一覧", admin_messages_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-item nav-link text-light' %>
                <% elsif request.fullpath.include?("/admin") %>
                  <%= link_to "About", public_homes_about_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-item nav-link text-light' %>
                  <%#= link_to "新規登録", new_admin_registration_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログイン", new_admin_session_path, class: 'nav-item nav-link text-light' %>
                <% elsif customer_signed_in? %>
                  <%= link_to "マイページ", public_customer_path(current_customer.id), class: 'nav-item nav-link text-light' %>
                  <%= link_to "商品一覧", public_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "カート", public_cart_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "メッセージ", public_contact_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-item nav-link text-light' %>
                <% else %>
                  <%= link_to "About", public_homes_about_path, class: 'nav-item nav-link text-light' %>
                  <%#= link_to "商品一覧", public_items_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "新規登録", new_customer_registration_path, class: 'nav-item nav-link text-light' %>
                  <%= link_to "ログイン", new_customer_session_path, class: 'nav-item nav-link text-light' %>
                <% end %>
              </div>
            </div>
            </div>
            <div class="col-md-12">
              <!-- 下段に検索枠を配置 -->
              <%#= render 'layouts/search' %>
            </div>
          </div>
        </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetOrder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2617833cd2.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&display=swap" rel="stylesheet">
  </head>
  
  <style>
    header{
      background-color: #FFC0CB;
      color:  #808080;
      padding: 20px;
    }
    
    main{
      padding-top: 5vh;
      padding-bottom: 5vh;
    }
    
    body{
      font-family: "Noto Sans JP", sans-serif;
    }
  </style>
  
  <body class="d-flex flex-column min-vh-100" style="background-color: #FFFFE0;">
    <%= render 'layouts/header' %>
    <% if notice %>
      <div class="alert alert-warning" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <main class="flex-grow-1">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>